// Description: This file contains the list of all the books of the bible and their abbreviations
// the first item in each array is the most common abbreviation and is the one used by API.Bible
export const BibleBooksMap: { [key: string]: Array<string> } = {
  genesis: ['gen', 'gn', 'ge'],
  exodus: ['exo', 'ex', 'exod'],
  leviticus: ['lev', 'lv', 'le'],
  numbers: ['num', 'nm', 'nu'],
  deuteronomy: ['deu', 'dt', 'deut'],
  joshua: ['jos', 'jsh', 'josh'],
  judges: ['jdg', 'jg', 'judg'],
  ruth: ['rut', 'ru'],
  '1 samuel': ['1sa', '1sm', '1sam', '1 sa', '1 sm', '1 sam'],
  '2 samuel': ['2sa', '2sm', '2sam', '2 sa', '2 sm', '2 sam'],
  '1 kings': ['1ki', '1ki', '1kgs', '1 ki', '1 ki', '1 kgs'],
  '2 kings': ['2ki', '2ki', '2kgs', '2 ki', '2 ki', '2 kgs'],
  '1 chronicles': ['1ch', '1chr', '1chron', '1 ch', '1 chr', '1 chron'],
  '2 chronicles': ['2ch', '2chr', '2chron', '2 ch', '2 chr', '2 chron'],
  ezra: ['ezr', 'ez'],
  nehemiah: ['neh', 'ne'],
  esther: ['est', 'es'],
  job: ['job', 'jb'],
  psalm: ['psa', 'ps', 'psalms'],
  proverbs: ['pro', 'pr', 'prov'],
  ecclesiastes: ['ecc', 'ec', 'eccl'],
  'song of solomon': ['sng', 'sos', 'song', 'so'],
  isaiah: ['isa', 'is'],
  jeremiah: ['jer', 'je'],
  lamentations: ['lam', 'la'],
  ezekiel: ['ezk', 'ezek'],
  daniel: ['dan', 'da', 'dn'],
  hosea: ['hos', 'ho'],
  joel: ['jol', 'joe'],
  amos: ['amo', 'am'],
  obadiah: ['oba', 'ob'],
  jonah: ['jon', 'jnh'],
  micah: ['mic', 'mi'],
  nahum: ['nam', 'nah', 'na'],
  habakkuk: ['hab', 'hk'],
  zephaniah: ['zep', 'zp'],
  haggai: ['hag', 'hg'],
  zechariah: ['zec', 'zc'],
  malachi: ['mal', 'ml'],
  matthew: ['mat', 'mt', 'matt'],
  mark: ['mrk', 'mk', 'mr'],
  luke: ['luk', 'lk', 'lu'],
  john: ['jhn', 'jn', 'joh', 'jo'],
  acts: ['act', 'ac'],
  romans: ['rom', 'ro', 'rm'],
  '1 corinthians': ['1co', '1cor', '1 co', '1 cor'],
  '2 corinthians': ['1co', '1cor', '1 co', '1 cor'],
  galatians: ['gal', 'ga', 'gl'],
  ephesians: ['eph', 'ep'],
  philippians: ['php', 'ph', 'phil'],
  colossians: ['col', 'co'],
  '1 thessalonians': ['1th', '1thes', '1 th', '1 thes'],
  '2 thessalonians': ['2th', '2thes', '2 th', '2 thes'],
  '1 timothy': ['1ti', '1tim', '1 ti', '1 tim'],
  '2 timothy': ['2ti', '2tim', '2 ti', '2 tim'],
  titus: ['tit', 'ti', 'tt'],
  philemon: ['phm', 'philem'],
  hebrews: ['heb', 'he'],
  james: ['jas', 'jam', 'ja'],
  '1 peter': ['1pe', '1pet', '1 pe', '1 pet'],
  '2 peter': ['2pe', '2pet', '2 pe', '2 pet'],
  '1 john': ['1jn', '1jhn', '1jo', '1joh', '1 jn', '1 jhn', '1 jo', '1 joh'],
  '2 john': ['2jn', '2jhn', '2jo', '2joh', '2 jn', '2 jhn', '2 jo', '2 joh'],
  '3 john': ['3jn', '3jhn', '3jo', '4joh', '3 jn', '3 jhn', '3 jo', '3 joh'],
  jude: ['jud', 'ju'],
  revelation: ['rev', 're', 'rev'],
};
