steps:
  - id: install
    name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  
  - id: lint
    name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'lint']
  
  - id: install-playwright
    name: 'ubuntu'
    args: ['npx', 'playwright', 'install', 'chromium', '--with-deps']
 
  - id: install-playwright-deps
    name: 'ubuntu'
    args: ['npx', 'playwright', 'install-deps']

  - id: tests
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VITE_CLOUDINARY_API_KEY=VITE_CLOUDINARY_API_KEY
        VITE_CLOUDINARY_SECRET=VITE_CLOUDINARY_SECRET
        npx playwright test tests/unit/*.ts && npx playwright test tests/e2e/*.ts
    secretEnv: ['VITE_CLOUDINARY_API_KEY', 'VITE_CLOUDINARY_SECRET']
availableSecrets:
  secretManager:
    - env: 'VITE_CLOUDINARY_API_KEY'
      versionName: projects/$PROJECT_ID/secrets/VITE_CLOUDINARY_API_KEY/versions/1
    - env: 'VITE_CLOUDINARY_SECRET'
      versionName: projects/$PROJECT_ID/secrets/VITE_CLOUDINARY_SECRET/versions/1
