steps:
  - id: install
    name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--ignore-scripts']

  - id: lint
    name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'lint']

  - id: tests
    name: 'mcr.microsoft.com/playwright'
    entrypoint: 'npm'
    args: ['run', 'test']
    secretEnv:
      [
        'VITE_CLOUDINARY_API_KEY',
        'VITE_CLOUDINARY_SECRET',
        'VITE_BIBLE_API_KEY',
        'VITE_S3_ACCESS_KEY_ID',
        'VITE_S3_SECRET_ACCESS_KEY',
        'VITE_S3_BUCKET',
        'VITE_S3_ENDPOINT',
        'VITE_S3_REGION',
      ]
availableSecrets:
  secretManager:
    - env: 'VITE_CLOUDINARY_API_KEY'
      versionName: projects/$PROJECT_ID/secrets/VITE_CLOUDINARY_API_KEY/versions/1
    - env: 'VITE_CLOUDINARY_SECRET'
      versionName: projects/$PROJECT_ID/secrets/VITE_CLOUDINARY_SECRET/versions/1
    - env: 'VITE_BIBLE_API_KEY'
      versionName: projects/$PROJECT_ID/secrets/VITE_BIBLE_API_KEY/versions/1
    - env: 'VITE_S3_ACCESS_KEY_ID'
      versionName: projects/$PROJECT_ID/secrets/VITE_S3_ACCESS_KEY_ID/versions/1
    - env: 'VITE_S3_SECRET_ACCESS_KEY'
      versionName: projects/$PROJECT_ID/secrets/VITE_S3_SECRET_ACCESS_KEY/versions/1
    - env: 'VITE_S3_BUCKET'
      versionName: projects/$PROJECT_ID/secrets/VITE_S3_BUCKET/versions/1
    - env: 'VITE_S3_ENDPOINT'
      versionName: projects/$PROJECT_ID/secrets/VITE_S3_ENDPOINT/versions/1
    - env: 'VITE_S3_REGION'
      versionName: projects/$PROJECT_ID/secrets/VITE_S3_REGION/versions/1
