steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - |
        docker build --no-cache \
          --build-arg VITE_CLOUDINARY_API_KEY=$$VITE_CLOUDINARY_API_KEY \
          --build-arg VITE_CLOUDINARY_SECRET=$$VITE_CLOUDINARY_SECRET \
          --build-arg VITE_BIBLE_API_KEY=$$VITE_BIBLE_API_KEY \
          --build-arg VITE_S3_ACCESS_KEY_ID=$$VITE_S3_ACCESS_KEY_ID \
          --build-arg VITE_S3_SECRET_ACCESS_KEY=$$VITE_S3_SECRET_ACCESS_KEY \
          --build-arg VITE_S3_BUCKET=$$VITE_S3_BUCKET \
          --build-arg VITE_S3_ENDPOINT=$$VITE_S3_ENDPOINT \
          --build-arg VITE_S3_REGION=$$VITE_S3_REGION \
          -t $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA \
          .
    entrypoint: bash
    secretEnv:
      [
        'VITE_CLOUDINARY_API_KEY',
        'VITE_CLOUDINARY_SECRET',
        'VITE_BIBLE_API_KEY',
        'VITE_S3_ACCESS_KEY_ID',
        'VITE_S3_SECRET_ACCESS_KEY',
      ]
  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

  - id: Deploy
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _GCR_HOSTNAME: eu.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: playground
  _LABELS: gcb-trigger-id=fa5fed62-1133-423c-a580-25243991619b
  _TRIGGER_ID: fa5fed62-1133-423c-a580-25243991619b
  _DEPLOY_REGION: europe-west1
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - playground
availableSecrets:
  secretManager:
    - env: 'VITE_CLOUDINARY_API_KEY'
      versionName: projects/$PROJECT_ID/secrets/VITE_CLOUDINARY_API_KEY/versions/1
    - env: 'VITE_CLOUDINARY_SECRET'
      versionName: projects/$PROJECT_ID/secrets/VITE_CLOUDINARY_SECRET/versions/1
    - env: 'VITE_BIBLE_API_KEY'
      versionName: projects/$PROJECT_ID/secrets/VITE_BIBLE_API_KEY/versions/1
    - env: 'VITE_S3_ACCESS_KEY_ID'
      versionName: projects/$PROJECT_ID/secrets/VITE_S3_ACCESS_KEY_ID/versions/1
    - env: 'VITE_S3_SECRET_ACCESS_KEY'
      versionName: projects/$PROJECT_ID/secrets/VITE_S3_SECRET_ACCESS_KEY/versions/1
