steps:
  # - id: Test
  #   name: 'gcr.io/cloud-builders/docker'
  #   entrypoint: 'bash'
  #   args: ['-c', 'echo VITE_CLOUDINARY_API_KEY=$$VITE_CLOUDINARY_API_KEY && echo VITE_CLOUDINARY_SECRET=$$VITE_CLOUDINARY_SECRET']
  #   secretEnv: ['VITE_CLOUDINARY_API_KEY', 'VITE_CLOUDINARY_SECRET']
  # - id: Test2
  #   name: 'gcr.io/cloud-builders/docker'
  #   entrypoint: 'bash'
  #   args: ['-c', "./ops/script.sh $$VITE_CLOUDINARY_API_KEY $$VITE_CLOUDINARY_SECRET"]
  #   secretEnv: ['VITE_CLOUDINARY_API_KEY', 'VITE_CLOUDINARY_SECRET']
  
  - id: Build
    name: gcr.io/cloud-builders/docker 
    entrypoint: bash
    # args:
    #   - build
    #   - "--no-cache"
    #   - "-t"
    #   - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
    #   - "--build-arg"
    #   - "VITE_CLOUDINARY_API_KEY=$$VITE_CLOUDINARY_API_KEY"
    #   - .
    #   - "-f"
    #   - Dockerfile
    args: ['-c', 'docker build -t $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA --build-arg VITE_CLOUDINARY_API_KEY=$$VITE_CLOUDINARY_API_KEY VITE_CLOUDINARY_SECRET=$$VITE_CLOUDINARY_SECRET -f Dockerfile'] 
    secretEnv: ['VITE_CLOUDINARY_API_KEY', 'VITE_CLOUDINARY_SECRET']
  # - id: Push
  #   name: gcr.io/cloud-builders/docker
  #   args:
  #     - push
  #     - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"

  # - id: Deploy
  #   name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
  #   args:
  #     - run
  #     - services
  #     - update
  #     - $_SERVICE_NAME
  #     - "--platform=managed"
  #     - "--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
  #     - >-
  #       --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
  #     - "--region=$_DEPLOY_REGION"
  #     - "--quiet"
  #   entrypoint: gcloud
images:
  - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _GCR_HOSTNAME: eu.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: playground
  _LABELS: gcb-trigger-id=fa5fed62-1133-423c-a580-25243991619b
  _TRIGGER_ID: fa5fed62-1133-423c-a580-25243991619b
  _DEPLOY_REGION: europe-west1
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - playground
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/VITE_CLOUDINARY_API_KEY/versions/1
      env: 'VITE_CLOUDINARY_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/VITE_CLOUDINARY_SECRET/versions/1
      env: 'VITE_CLOUDINARY_SECRET'

# ["build","--no-cache","-t","$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA","--build-arg","VITE_CLOUDINARY_API_KEY=$$VITE_CLOUDINARY_API_KEY",".","-f","Dockerfile"] 